graph LR
    linkStyle default interpolate basis
    A([Start])
    A-->B[Strategy Development]
    B-->C[Optimization Environment]
    C-->D{Good strategy}
    D-->|No|B
    D-->|Yes|E[Live API]
    E-->F[Good Strategy]
    F-->|No|B
    F-->|Yes|G{Seasonal}
    G-->|No|E
    G-->|Yes|H{In Season}
    H-->|No|I[Wait]
    H-->|Yes|E
    I-->G
